sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test -- --coverage

after_success:
  - docker build -t romanrzes/multi-client ./client
  - docker build -t romanrzes/multi-nginx ./nginx
  - docker build -t romanrzes/multi-server ./server
  - docker build -t romanrzes/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tako thos imagas and push them to docker hub
  - docker push romanrzes/multi-client
  - docker push romanrzes/multi-nging
  - docker push romanrzes/multi-server
  - docker push romanrzes/multi-worker
